from typing import TypeAlias

Player: TypeAlias = int

class PlayerMove:
    player: Player
    data: str

    def __str__(self) -> str: ...


class Battle:
    num_players: int

    def send_to(self, player: Player, data: str): ...
    def wait(self) -> PlayerMove: ...
    def wait_for(self, player: Player) -> PlayerMove: ...
    def set_points(self, player: Player, count: int): ...
    def add_points(self, player: Player, count: int): ...
    def end_due(self, data: str): ...
    def end(self): ...



def get_battle() -> Battle: ...
