# Generated by Django 4.2 on 2023-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invokerreport',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ok'), (1, 'Error')], default=0, verbose_name='Статус'),
        ),
    ]
