# Generated by Django 4.2.5 on 2023-11-17 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoker', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilerreport',
            name='invoker_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoker.invokerreport', verbose_name='Репорт инвокера'),
        ),
        migrations.AlterField(
            model_name='compilerreport',
            name='time',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Время выполнения'),
        ),
    ]
