# Generated by Django 4.2.9 on 2024-01-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentsystem',
            options={'managed': False},
        ),
    ]
