# Generated by Django 4.2 on 2023-11-19 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoker', '0002_alter_invokerreport_exit_code'),
        ('app', '0002_invokerreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_id', models.IntegerField(default=0, verbose_name='Battle id')),
                ('invoker_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoker.invokerreport', verbose_name='InvokerReport')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_players', models.IntegerField()),
                ('ideal_solution', models.FileField(blank=True, null=True, upload_to=models.CharField(max_length=50), verbose_name='Ideal_solution')),
                ('play', models.FileField(blank=True, null=True, upload_to=models.CharField(max_length=50), verbose_name='Play')),
            ],
        ),
        migrations.CreateModel(
            name='PlayersInBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(blank=True, editable=False, null=True, verbose_name='Путь к файлу')),
                ('strategy_id', models.IntegerField(default=0, verbose_name='id стратегии в Battle')),
                ('is_winner', models.BooleanField(default=False, verbose_name='Победитель')),
            ],
        ),
        migrations.AlterField(
            model_name='compilerreport',
            name='invoker_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoker.invokerreport', verbose_name='Репорт инвокера'),
        ),
        migrations.AlterField(
            model_name='compilerreport',
            name='time',
            field=models.DurationField(default=datetime.timedelta, verbose_name='Время выполнения'),
        ),
        migrations.DeleteModel(
            name='InvokerReport',
        ),
    ]
