[package]
name = "libgame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0", features = [] }
serde = { version = "1.0.193", features = ["derive"] }
indexmap = { version = "2.1.0", features = [] }
