class Frame:
    data: list[list[tuple[int, int, int]]]

    draw_line(self, start_x: int, start_y: int, end_x: int, end_y: int, color: tuple[int, int, int]): ...
    draw_circle(self, x: int, y: int, radius: int, color: tuple[int, int, int], fill: bool): ...
    draw_rectangle(self, x1: int, y1: int, x2: int, y2: int, color: tuple[int, int, int], fill: bool): ...

def get_frame(width: int, height: int, color: tuple[int, int, int]) -> Frame: ...