# Generated by Django 4.2.9 on 2024-04-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='invoker_files', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='InvokerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Команда')),
                ('time_start', models.DateTimeField(blank=True, verbose_name='Время начала')),
                ('time_end', models.DateTimeField(blank=True, verbose_name='Время завершения')),
                ('exit_code', models.IntegerField(blank=True, null=True, verbose_name='Код выхода')),
                ('output', models.TextField(blank=True, verbose_name='Результат')),
                ('timelimit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ограничение по времени')),
                ('status', models.IntegerField(choices=[(0, 'Ok'), (1, 'Re'), (2, 'Tl')], default=0, verbose_name='Статус')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('input_files', models.ManyToManyField(blank=True, related_name='input_invoker', to='invoker.file', verbose_name='Загружённые файлы')),
                ('preserved_files', models.ManyToManyField(blank=True, related_name='preserved_invoker', to='invoker.file', verbose_name='Сохранённые файлы')),
            ],
            options={
                'verbose_name': 'Репорт инвокера',
                'verbose_name_plural': 'Репорты инвокера',
            },
        ),
    ]
