# Generated by Django 4.2.5 on 2023-11-17 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvokerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Команда')),
                ('time_start', models.DateTimeField(blank=True, verbose_name='Время начала')),
                ('time_end', models.DateTimeField(blank=True, verbose_name='Время завершения')),
                ('exit_code', models.IntegerField(verbose_name='Код выхода')),
                ('output', models.TextField(blank=True, verbose_name='Результат')),
                ('status', models.IntegerField(choices=[(0, 'Ok'), (1, 'Re'), (2, 'Tl')], default=0, verbose_name='Статус')),
                ('error', models.TextField(blank=True, editable=False, null=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Репорт инвокера',
                'verbose_name_plural': 'Репорты инвокера',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('file', models.FileField(upload_to='invoker_report_files', verbose_name='Файл')),
                ('invoker_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='invoker.invokerreport', verbose_name='Инвокер репорт')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
