# Generated by Django 4.2 on 2023-11-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invokerreport',
            name='exit_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код выхода'),
        ),
    ]
