# Generated by Django 4.2.5 on 2023-11-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='invoker_report',
        ),
        migrations.AddField(
            model_name='invokerreport',
            name='files',
            field=models.ManyToManyField(blank=True, to='invoker.file', verbose_name='Файлы'),
        ),
    ]
