# Generated by Django 4.2.5 on 2023-11-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoker', '0002_remove_file_invoker_report_invokerreport_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invokerreport',
            name='files',
        ),
        migrations.AddField(
            model_name='invokerreport',
            name='input_files',
            field=models.ManyToManyField(blank=True, related_name='input_invoker', to='invoker.file', verbose_name='Загружённые файлы'),
        ),
        migrations.AddField(
            model_name='invokerreport',
            name='preserved_files',
            field=models.ManyToManyField(blank=True, related_name='preserved_invoker', to='invoker.file', verbose_name='Сохранённые файлы'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='invoker_files', verbose_name='Файл'),
        ),
    ]
